address ERR_PNPM_OUTDATED_LOCKFILE
Run pnpm install --frozen-lockfile --filter expo-desktop --filter expo-desktop-config-plugins --filter expo-desktop-modules-core --filter expo-desktop-prebuild-config --filter expo-desktop-stubs
Scope: 5 of 10 workspace projects
[ERR_PNPM_OUTDATED_LOCKFILE] Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with <ROOT>/packages/expo-desktop-prebuild-config/package.json

Note that in CI environments this setting is true by default. If you still need to run install in such cases, use "pnpm install --no-frozen-lockfile"

  Failure reason:
  specifiers in the lockfile don't match specifiers in package.json:
* 1 dependencies are mismatched:
  - expo-desktop-config-plugins (lockfile: workspace:^1.1.21, manifest: workspace:^1.1.22)

Error: Process completed with exit code 1.